//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingVoiceSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataDrivenRule
    {
        public int QuestionId { get; set; }
        public int DataId { get; set; }
        public string Answer { get; set; }
        public string ApprovedBy { get; set; }
        public string LastEditedBy { get; set; }
    
        public virtual ApprovedDataRuleQuestion ApprovedDataRuleQuestion { get; set; }
    }
}
