//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BingVoiceSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public string MovieName { get; set; }
        public int MovieId { get; set; }
        public string LastEditedBy { get; set; }
        public string CreatedBy { get; set; }
    }
}
